import * as React from 'react';
import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import { Stack, Box, Button } from '@mui/material';
import { HeaderButton } from './styles';
import { useRouter } from 'next/router';

type PageWrapperProps = {
  title?: string;
  children?: React.ReactNode;
};

const PageWrapper = ({
  title = 'Book Recommender',
  children
}: PageWrapperProps): JSX.Element => {
  const { pathname } = useRouter();

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack style={{ minHeight: '100vh' }}>
        <Stack
          component="header"
          flexDirection="row"
          justifyContent="space-between"
          style={{
            padding: '24px',
            boxShadow: '0px 5px 5px #ccc'
          }}
        >
          <Box>
            <h1>Book recommender</h1>
          </Box>
          <Stack flexDirection="row">
            {pathname !== '/' && (
              <Link href="/">
                <HeaderButton variant="contained">Home page</HeaderButton>
              </Link>
            )}
            {pathname !== '/login' && (
              <Link href="/login">
                <HeaderButton variant="contained">Log in</HeaderButton>
              </Link>
            )}
            {pathname !== '/register' && (
              <Link href="/register">
                <HeaderButton variant="contained">Register</HeaderButton>
              </Link>
            )}
          </Stack>
        </Stack>
        <Stack component="main" flex="1">
          {children}
        </Stack>
        <Stack
          component="footer"
          flexDirection="row"
          justifyContent="space-between"
          style={{
            padding: '24px',
            boxShadow: '0px -5px 5px #ccc'
          }}
        >
          &copy; 2022 Marta Dychała
        </Stack>
      </Stack>
    </>
  );
};

export default PageWrapper;
